
#
#    ______          __     ____                 __  ______ 
#   / ____/___  ____/ /__  / __ \____  _____    / / / / __ \
#  / /   / __ \/ __  / _ \/ / / / __ \/ ___/   / /_/ / / / /
# / /___/ /_/ / /_/ /  __/ /_/ / /_/ (__  )   / __  / /_/ / 
# \____/\____/\__,_/\___/\____/ .___/____/   /_/ /_/\___\_\ 
#                            /_/
#
#
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
